#############################################################################
# Makefile for building: NetworkSimulationPlatform
# Generated by qmake (2.01a) (Qt 4.8.4) on: Mon Mar 9 15:50:00 2015
# Project:  NetworkSimulationPlatform.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.8.4/bin/qmake -o Makefile NetworkSimulationPlatform.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -Wno-unused-parameter -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.8.4/mkspecs/linux-g++-64 -I. -I/usr/local/Trolltech/Qt-4.8.4/include/QtCore -I/usr/local/Trolltech/Qt-4.8.4/include/QtGui -I/usr/local/Trolltech/Qt-4.8.4/include -I. -IUI
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/Qt-4.8.4/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.8.4/lib -lQtGui -L/usr/local/Trolltech/Qt-4.8.4/lib -L/usr/X11R6/lib64 -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.8.4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		NetworkSimulationPlatform.cpp \
		CUnitboxWidget.cpp \
		CNewSwitcher.cpp \
		CNetworkEditWidget.cpp \
		BoundingRectItem.cpp \
		Device/CSwitherConfigure.cpp \
		Device/CSwitcher.cpp \
		Device/CNetworkPort.cpp \
		Device/CItemGroup.cpp \
		Clink.cpp \
		CWizard.cpp \
		CPortDialog.cpp \
		DragNetwork.cpp \
		PlacementAlgorithm.cpp \
		CTaskConfigDialog.cpp \
		CPartitionNumDialog.cpp \
		Application/CEchoAppTaskDialog.cpp \
		Application/COnOffAppTaskDialog.cpp \
		Application/CBulkAppTaskDialog.cpp moc_NetworkSimulationPlatform.cpp \
		moc_CNetworkEditWidget.cpp \
		moc_CNewSwitcher.cpp \
		moc_CSwitherConfigure.cpp \
		moc_CWizard.cpp \
		moc_CPortDialog.cpp \
		moc_CTaskConfigDialog.cpp \
		moc_CPartitionNumDialog.cpp \
		moc_CEchoAppTaskDialog.cpp \
		moc_COnOffAppTaskDialog.cpp \
		moc_CBulkAppTaskDialog.cpp \
		qrc_NetworkSimulationPlatform.cpp
OBJECTS       = main.o \
		NetworkSimulationPlatform.o \
		CUnitboxWidget.o \
		CNewSwitcher.o \
		CNetworkEditWidget.o \
		BoundingRectItem.o \
		CSwitherConfigure.o \
		CSwitcher.o \
		CNetworkPort.o \
		CItemGroup.o \
		Clink.o \
		CWizard.o \
		CPortDialog.o \
		DragNetwork.o \
		PlacementAlgorithm.o \
		CTaskConfigDialog.o \
		CPartitionNumDialog.o \
		CEchoAppTaskDialog.o \
		COnOffAppTaskDialog.o \
		CBulkAppTaskDialog.o \
		moc_NetworkSimulationPlatform.o \
		moc_CNetworkEditWidget.o \
		moc_CNewSwitcher.o \
		moc_CSwitherConfigure.o \
		moc_CWizard.o \
		moc_CPortDialog.o \
		moc_CTaskConfigDialog.o \
		moc_CPartitionNumDialog.o \
		moc_CEchoAppTaskDialog.o \
		moc_COnOffAppTaskDialog.o \
		moc_CBulkAppTaskDialog.o \
		qrc_NetworkSimulationPlatform.o
DIST          = /usr/local/Trolltech/Qt-4.8.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/include_source_dir.prf \
		NetworkSimulationPlatform.pro
QMAKE_TARGET  = NetworkSimulationPlatform
DESTDIR       = 
TARGET        = NetworkSimulationPlatform

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): UI/ui_NetworkSimulationPlatform.h UI/ui_CSwitherConfigure.h UI/ui_CNewSwitcher.h UI/ui_CDeviceConfigure.h UI/ui_wizard.h UI/ui_CPortDialog.h UI/ui_CTaskConfigDialog.h UI/ui_CEchoAppTaskDialog.h UI/ui_CPartitionNumDialog.h UI/ui_COnOffAppTaskDialog.h UI/ui_CBulkAppTaskDialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: NetworkSimulationPlatform.pro  /usr/local/Trolltech/Qt-4.8.4/mkspecs/linux-g++-64/qmake.conf /usr/local/Trolltech/Qt-4.8.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.8.4/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.8.4/lib/libQtCore.prl
	$(QMAKE) -o Makefile NetworkSimulationPlatform.pro
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.8.4/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.8.4/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile NetworkSimulationPlatform.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/NetworkSimulationPlatform1.0.0 || $(MKDIR) .tmp/NetworkSimulationPlatform1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/NetworkSimulationPlatform1.0.0/ && $(COPY_FILE) --parents NetworkSimulationPlatform.h StructFile.h CUnitboxWidget.h CNetworkEditWidget.h label.h CNewSwitcher.h BoundingRectItem.h Device/CSwitherConfigure.h Device/CSwitcher.h Device/CNetworkPort.h Device/CModel.h Device/CItemGroup.h Device/CBaseObject.h Clink.h CWizard.h CPortDialog.h DragNetwork.h PlacementAlgorithm.h StructDefine.h CTaskConfigDialog.h CPartitionNumDialog.h Application/CEchoAppTaskDialog.h Application/COnOffAppTaskDialog.h Application/CBulkAppTaskDialog.h .tmp/NetworkSimulationPlatform1.0.0/ && $(COPY_FILE) --parents NetworkSimulationPlatform.qrc .tmp/NetworkSimulationPlatform1.0.0/ && $(COPY_FILE) --parents main.cpp NetworkSimulationPlatform.cpp CUnitboxWidget.cpp CNewSwitcher.cpp CNetworkEditWidget.cpp BoundingRectItem.cpp Device/CSwitherConfigure.cpp Device/CSwitcher.cpp Device/CNetworkPort.cpp Device/CItemGroup.cpp Clink.cpp CWizard.cpp CPortDialog.cpp DragNetwork.cpp PlacementAlgorithm.cpp CTaskConfigDialog.cpp CPartitionNumDialog.cpp Application/CEchoAppTaskDialog.cpp Application/COnOffAppTaskDialog.cpp Application/CBulkAppTaskDialog.cpp .tmp/NetworkSimulationPlatform1.0.0/ && $(COPY_FILE) --parents NetworkSimulationPlatform.ui CSwitherConfigure.ui CNewSwitcher.ui CDeviceConfigure.ui wizard.ui CPortDialog.ui CTaskConfigDialog.ui CEchoAppTaskDialog.ui CPartitionNumDialog.ui COnOffAppTaskDialog.ui CBulkAppTaskDialog.ui .tmp/NetworkSimulationPlatform1.0.0/ && (cd `dirname .tmp/NetworkSimulationPlatform1.0.0` && $(TAR) NetworkSimulationPlatform1.0.0.tar NetworkSimulationPlatform1.0.0 && $(COMPRESS) NetworkSimulationPlatform1.0.0.tar) && $(MOVE) `dirname .tmp/NetworkSimulationPlatform1.0.0`/NetworkSimulationPlatform1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/NetworkSimulationPlatform1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_NetworkSimulationPlatform.cpp moc_CNetworkEditWidget.cpp moc_CNewSwitcher.cpp moc_CSwitherConfigure.cpp moc_CWizard.cpp moc_CPortDialog.cpp moc_CTaskConfigDialog.cpp moc_CPartitionNumDialog.cpp moc_CEchoAppTaskDialog.cpp moc_COnOffAppTaskDialog.cpp moc_CBulkAppTaskDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_NetworkSimulationPlatform.cpp moc_CNetworkEditWidget.cpp moc_CNewSwitcher.cpp moc_CSwitherConfigure.cpp moc_CWizard.cpp moc_CPortDialog.cpp moc_CTaskConfigDialog.cpp moc_CPartitionNumDialog.cpp moc_CEchoAppTaskDialog.cpp moc_COnOffAppTaskDialog.cpp moc_CBulkAppTaskDialog.cpp
moc_NetworkSimulationPlatform.cpp: StructFile.h \
		CUnitboxWidget.h \
		label.h \
		CNetworkEditWidget.h \
		CNewSwitcher.h \
		UI/ui_CNewSwitcher.h \
		CPortDialog.h \
		UI/ui_CPortDialog.h \
		CWizard.h \
		UI/ui_wizard.h \
		Device/CSwitherConfigure.h \
		UI/ui_CSwitherConfigure.h \
		Device/CSwitcher.h \
		Device/CBaseObject.h \
		Device/CItemGroup.h \
		Device/CNetworkPort.h \
		Clink.h \
		BoundingRectItem.h \
		DragNetwork.h \
		StructDefine.h \
		PlacementAlgorithm.h \
		CTaskConfigDialog.h \
		Application/CEchoAppTaskDialog.h \
		Application/COnOffAppTaskDialog.h \
		Application/CBulkAppTaskDialog.h \
		UI/ui_NetworkSimulationPlatform.h \
		NetworkSimulationPlatform.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) NetworkSimulationPlatform.h -o moc_NetworkSimulationPlatform.cpp

moc_CNetworkEditWidget.cpp: CNewSwitcher.h \
		UI/ui_CNewSwitcher.h \
		StructFile.h \
		CPortDialog.h \
		UI/ui_CPortDialog.h \
		CWizard.h \
		UI/ui_wizard.h \
		Device/CSwitherConfigure.h \
		UI/ui_CSwitherConfigure.h \
		Device/CSwitcher.h \
		Device/CBaseObject.h \
		Device/CItemGroup.h \
		Device/CNetworkPort.h \
		Clink.h \
		CUnitboxWidget.h \
		label.h \
		BoundingRectItem.h \
		DragNetwork.h \
		StructDefine.h \
		PlacementAlgorithm.h \
		CTaskConfigDialog.h \
		Application/CEchoAppTaskDialog.h \
		Application/COnOffAppTaskDialog.h \
		Application/CBulkAppTaskDialog.h \
		CNetworkEditWidget.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) CNetworkEditWidget.h -o moc_CNetworkEditWidget.cpp

moc_CNewSwitcher.cpp: UI/ui_CNewSwitcher.h \
		StructFile.h \
		CNewSwitcher.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) CNewSwitcher.h -o moc_CNewSwitcher.cpp

moc_CSwitherConfigure.cpp: UI/ui_CSwitherConfigure.h \
		StructFile.h \
		Device/CSwitherConfigure.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) Device/CSwitherConfigure.h -o moc_CSwitherConfigure.cpp

moc_CWizard.cpp: UI/ui_wizard.h \
		CWizard.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) CWizard.h -o moc_CWizard.cpp

moc_CPortDialog.cpp: StructFile.h \
		UI/ui_CPortDialog.h \
		CPortDialog.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) CPortDialog.h -o moc_CPortDialog.cpp

moc_CTaskConfigDialog.cpp: Application/CEchoAppTaskDialog.h \
		CNewSwitcher.h \
		UI/ui_CNewSwitcher.h \
		StructFile.h \
		Device/CSwitcher.h \
		Device/CBaseObject.h \
		Application/COnOffAppTaskDialog.h \
		Application/CBulkAppTaskDialog.h \
		CTaskConfigDialog.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) CTaskConfigDialog.h -o moc_CTaskConfigDialog.cpp

moc_CPartitionNumDialog.cpp: CPartitionNumDialog.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) CPartitionNumDialog.h -o moc_CPartitionNumDialog.cpp

moc_CEchoAppTaskDialog.cpp: CNewSwitcher.h \
		UI/ui_CNewSwitcher.h \
		StructFile.h \
		Device/CSwitcher.h \
		Device/CBaseObject.h \
		Application/CEchoAppTaskDialog.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) Application/CEchoAppTaskDialog.h -o moc_CEchoAppTaskDialog.cpp

moc_COnOffAppTaskDialog.cpp: CNewSwitcher.h \
		UI/ui_CNewSwitcher.h \
		StructFile.h \
		Device/CSwitcher.h \
		Device/CBaseObject.h \
		Application/COnOffAppTaskDialog.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) Application/COnOffAppTaskDialog.h -o moc_COnOffAppTaskDialog.cpp

moc_CBulkAppTaskDialog.cpp: CNewSwitcher.h \
		UI/ui_CNewSwitcher.h \
		StructFile.h \
		Device/CSwitcher.h \
		Device/CBaseObject.h \
		Application/CBulkAppTaskDialog.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) Application/CBulkAppTaskDialog.h -o moc_CBulkAppTaskDialog.cpp

compiler_rcc_make_all: qrc_NetworkSimulationPlatform.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_NetworkSimulationPlatform.cpp
qrc_NetworkSimulationPlatform.cpp: NetworkSimulationPlatform.qrc \
		Resources/switcher.png \
		Resources/newItem.png \
		Resources/back.jpg \
		Resources/exit.png \
		Resources/zoomIn.png \
		Resources/single.png \
		Resources/save.png \
		Resources/zoomOut.png \
		Resources/layout.png \
		Resources/pc.png \
		Resources/double.png \
		Resources/open.png
	/usr/local/Trolltech/Qt-4.8.4/bin/rcc -name NetworkSimulationPlatform NetworkSimulationPlatform.qrc -o qrc_NetworkSimulationPlatform.cpp

compiler_image_collection_make_all: UI/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) UI/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: UI/ui_NetworkSimulationPlatform.h UI/ui_CSwitherConfigure.h UI/ui_CNewSwitcher.h UI/ui_CDeviceConfigure.h UI/ui_wizard.h UI/ui_CPortDialog.h UI/ui_CTaskConfigDialog.h UI/ui_CEchoAppTaskDialog.h UI/ui_CPartitionNumDialog.h UI/ui_COnOffAppTaskDialog.h UI/ui_CBulkAppTaskDialog.h
compiler_uic_clean:
	-$(DEL_FILE) UI/ui_NetworkSimulationPlatform.h UI/ui_CSwitherConfigure.h UI/ui_CNewSwitcher.h UI/ui_CDeviceConfigure.h UI/ui_wizard.h UI/ui_CPortDialog.h UI/ui_CTaskConfigDialog.h UI/ui_CEchoAppTaskDialog.h UI/ui_CPartitionNumDialog.h UI/ui_COnOffAppTaskDialog.h UI/ui_CBulkAppTaskDialog.h
UI/ui_NetworkSimulationPlatform.h: NetworkSimulationPlatform.ui
	/usr/local/Trolltech/Qt-4.8.4/bin/uic NetworkSimulationPlatform.ui -o UI/ui_NetworkSimulationPlatform.h

UI/ui_CSwitherConfigure.h: CSwitherConfigure.ui
	/usr/local/Trolltech/Qt-4.8.4/bin/uic CSwitherConfigure.ui -o UI/ui_CSwitherConfigure.h

UI/ui_CNewSwitcher.h: CNewSwitcher.ui
	/usr/local/Trolltech/Qt-4.8.4/bin/uic CNewSwitcher.ui -o UI/ui_CNewSwitcher.h

UI/ui_CDeviceConfigure.h: CDeviceConfigure.ui
	/usr/local/Trolltech/Qt-4.8.4/bin/uic CDeviceConfigure.ui -o UI/ui_CDeviceConfigure.h

UI/ui_wizard.h: wizard.ui
	/usr/local/Trolltech/Qt-4.8.4/bin/uic wizard.ui -o UI/ui_wizard.h

UI/ui_CPortDialog.h: CPortDialog.ui
	/usr/local/Trolltech/Qt-4.8.4/bin/uic CPortDialog.ui -o UI/ui_CPortDialog.h

UI/ui_CTaskConfigDialog.h: CTaskConfigDialog.ui
	/usr/local/Trolltech/Qt-4.8.4/bin/uic CTaskConfigDialog.ui -o UI/ui_CTaskConfigDialog.h

UI/ui_CEchoAppTaskDialog.h: CEchoAppTaskDialog.ui
	/usr/local/Trolltech/Qt-4.8.4/bin/uic CEchoAppTaskDialog.ui -o UI/ui_CEchoAppTaskDialog.h

UI/ui_CPartitionNumDialog.h: CPartitionNumDialog.ui
	/usr/local/Trolltech/Qt-4.8.4/bin/uic CPartitionNumDialog.ui -o UI/ui_CPartitionNumDialog.h

UI/ui_COnOffAppTaskDialog.h: COnOffAppTaskDialog.ui
	/usr/local/Trolltech/Qt-4.8.4/bin/uic COnOffAppTaskDialog.ui -o UI/ui_COnOffAppTaskDialog.h

UI/ui_CBulkAppTaskDialog.h: CBulkAppTaskDialog.ui
	/usr/local/Trolltech/Qt-4.8.4/bin/uic CBulkAppTaskDialog.ui -o UI/ui_CBulkAppTaskDialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp NetworkSimulationPlatform.h \
		StructFile.h \
		CUnitboxWidget.h \
		label.h \
		CNetworkEditWidget.h \
		CNewSwitcher.h \
		UI/ui_CNewSwitcher.h \
		CPortDialog.h \
		UI/ui_CPortDialog.h \
		CWizard.h \
		UI/ui_wizard.h \
		Device/CSwitherConfigure.h \
		UI/ui_CSwitherConfigure.h \
		Device/CSwitcher.h \
		Device/CBaseObject.h \
		Device/CItemGroup.h \
		Device/CNetworkPort.h \
		Clink.h \
		BoundingRectItem.h \
		DragNetwork.h \
		StructDefine.h \
		PlacementAlgorithm.h \
		CTaskConfigDialog.h \
		Application/CEchoAppTaskDialog.h \
		Application/COnOffAppTaskDialog.h \
		Application/CBulkAppTaskDialog.h \
		UI/ui_NetworkSimulationPlatform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

NetworkSimulationPlatform.o: NetworkSimulationPlatform.cpp NetworkSimulationPlatform.h \
		StructFile.h \
		CUnitboxWidget.h \
		label.h \
		CNetworkEditWidget.h \
		CNewSwitcher.h \
		UI/ui_CNewSwitcher.h \
		CPortDialog.h \
		UI/ui_CPortDialog.h \
		CWizard.h \
		UI/ui_wizard.h \
		Device/CSwitherConfigure.h \
		UI/ui_CSwitherConfigure.h \
		Device/CSwitcher.h \
		Device/CBaseObject.h \
		Device/CItemGroup.h \
		Device/CNetworkPort.h \
		Clink.h \
		BoundingRectItem.h \
		DragNetwork.h \
		StructDefine.h \
		PlacementAlgorithm.h \
		CTaskConfigDialog.h \
		Application/CEchoAppTaskDialog.h \
		Application/COnOffAppTaskDialog.h \
		Application/CBulkAppTaskDialog.h \
		UI/ui_NetworkSimulationPlatform.h \
		CPartitionNumDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NetworkSimulationPlatform.o NetworkSimulationPlatform.cpp

CUnitboxWidget.o: CUnitboxWidget.cpp CUnitboxWidget.h \
		label.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CUnitboxWidget.o CUnitboxWidget.cpp

CNewSwitcher.o: CNewSwitcher.cpp CNewSwitcher.h \
		UI/ui_CNewSwitcher.h \
		StructFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CNewSwitcher.o CNewSwitcher.cpp

CNetworkEditWidget.o: CNetworkEditWidget.cpp CNetworkEditWidget.h \
		CNewSwitcher.h \
		UI/ui_CNewSwitcher.h \
		StructFile.h \
		CPortDialog.h \
		UI/ui_CPortDialog.h \
		CWizard.h \
		UI/ui_wizard.h \
		Device/CSwitherConfigure.h \
		UI/ui_CSwitherConfigure.h \
		Device/CSwitcher.h \
		Device/CBaseObject.h \
		Device/CItemGroup.h \
		Device/CNetworkPort.h \
		Clink.h \
		CUnitboxWidget.h \
		label.h \
		BoundingRectItem.h \
		DragNetwork.h \
		StructDefine.h \
		PlacementAlgorithm.h \
		CTaskConfigDialog.h \
		Application/CEchoAppTaskDialog.h \
		Application/COnOffAppTaskDialog.h \
		Application/CBulkAppTaskDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CNetworkEditWidget.o CNetworkEditWidget.cpp

BoundingRectItem.o: BoundingRectItem.cpp BoundingRectItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BoundingRectItem.o BoundingRectItem.cpp

CSwitherConfigure.o: Device/CSwitherConfigure.cpp Device/CSwitherConfigure.h \
		UI/ui_CSwitherConfigure.h \
		StructFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CSwitherConfigure.o Device/CSwitherConfigure.cpp

CSwitcher.o: Device/CSwitcher.cpp Device/CSwitcher.h \
		Device/CBaseObject.h \
		StructFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CSwitcher.o Device/CSwitcher.cpp

CNetworkPort.o: Device/CNetworkPort.cpp Device/CNetworkPort.h \
		Device/CBaseObject.h \
		StructFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CNetworkPort.o Device/CNetworkPort.cpp

CItemGroup.o: Device/CItemGroup.cpp Device/CItemGroup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CItemGroup.o Device/CItemGroup.cpp

Clink.o: Clink.cpp Clink.h \
		Device/CNetworkPort.h \
		Device/CBaseObject.h \
		StructFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Clink.o Clink.cpp

CWizard.o: CWizard.cpp CWizard.h \
		UI/ui_wizard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CWizard.o CWizard.cpp

CPortDialog.o: CPortDialog.cpp CPortDialog.h \
		StructFile.h \
		UI/ui_CPortDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CPortDialog.o CPortDialog.cpp

DragNetwork.o: DragNetwork.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DragNetwork.o DragNetwork.cpp

PlacementAlgorithm.o: PlacementAlgorithm.cpp PlacementAlgorithm.h \
		StructDefine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PlacementAlgorithm.o PlacementAlgorithm.cpp

CTaskConfigDialog.o: CTaskConfigDialog.cpp CTaskConfigDialog.h \
		Application/CEchoAppTaskDialog.h \
		CNewSwitcher.h \
		UI/ui_CNewSwitcher.h \
		StructFile.h \
		Device/CSwitcher.h \
		Device/CBaseObject.h \
		Application/COnOffAppTaskDialog.h \
		Application/CBulkAppTaskDialog.h \
		UI/ui_CTaskConfigDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CTaskConfigDialog.o CTaskConfigDialog.cpp

CPartitionNumDialog.o: CPartitionNumDialog.cpp CPartitionNumDialog.h \
		UI/ui_CPartitionNumDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CPartitionNumDialog.o CPartitionNumDialog.cpp

CEchoAppTaskDialog.o: Application/CEchoAppTaskDialog.cpp Application/CEchoAppTaskDialog.h \
		CNewSwitcher.h \
		UI/ui_CNewSwitcher.h \
		StructFile.h \
		Device/CSwitcher.h \
		Device/CBaseObject.h \
		UI/ui_CEchoAppTaskDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CEchoAppTaskDialog.o Application/CEchoAppTaskDialog.cpp

COnOffAppTaskDialog.o: Application/COnOffAppTaskDialog.cpp Application/COnOffAppTaskDialog.h \
		CNewSwitcher.h \
		UI/ui_CNewSwitcher.h \
		StructFile.h \
		Device/CSwitcher.h \
		Device/CBaseObject.h \
		UI/ui_COnOffAppTaskDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o COnOffAppTaskDialog.o Application/COnOffAppTaskDialog.cpp

CBulkAppTaskDialog.o: Application/CBulkAppTaskDialog.cpp Application/CBulkAppTaskDialog.h \
		CNewSwitcher.h \
		UI/ui_CNewSwitcher.h \
		StructFile.h \
		Device/CSwitcher.h \
		Device/CBaseObject.h \
		UI/ui_CBulkAppTaskDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CBulkAppTaskDialog.o Application/CBulkAppTaskDialog.cpp

moc_NetworkSimulationPlatform.o: moc_NetworkSimulationPlatform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NetworkSimulationPlatform.o moc_NetworkSimulationPlatform.cpp

moc_CNetworkEditWidget.o: moc_CNetworkEditWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CNetworkEditWidget.o moc_CNetworkEditWidget.cpp

moc_CNewSwitcher.o: moc_CNewSwitcher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CNewSwitcher.o moc_CNewSwitcher.cpp

moc_CSwitherConfigure.o: moc_CSwitherConfigure.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CSwitherConfigure.o moc_CSwitherConfigure.cpp

moc_CWizard.o: moc_CWizard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CWizard.o moc_CWizard.cpp

moc_CPortDialog.o: moc_CPortDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CPortDialog.o moc_CPortDialog.cpp

moc_CTaskConfigDialog.o: moc_CTaskConfigDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CTaskConfigDialog.o moc_CTaskConfigDialog.cpp

moc_CPartitionNumDialog.o: moc_CPartitionNumDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CPartitionNumDialog.o moc_CPartitionNumDialog.cpp

moc_CEchoAppTaskDialog.o: moc_CEchoAppTaskDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CEchoAppTaskDialog.o moc_CEchoAppTaskDialog.cpp

moc_COnOffAppTaskDialog.o: moc_COnOffAppTaskDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_COnOffAppTaskDialog.o moc_COnOffAppTaskDialog.cpp

moc_CBulkAppTaskDialog.o: moc_CBulkAppTaskDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CBulkAppTaskDialog.o moc_CBulkAppTaskDialog.cpp

qrc_NetworkSimulationPlatform.o: qrc_NetworkSimulationPlatform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_NetworkSimulationPlatform.o qrc_NetworkSimulationPlatform.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

